apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  
  # here is label of replicaset itself
  labels:
    app: myapp
    type: front-end

spec:
  replicas: 3
  
  # conect replicaset to the pod (which pod will be managed by replicaset) 
  selector:
    matchLabels:
      type: front-end  
 
  template:
    metadata:
      # this is label of the pod that will be spin up by this replicaset
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
